---
development:
  dialect: "sqlite3"
  database: /home/forrest/Projects/go-servers/buffalo/coke_coke_development.sqlite

test:
  dialect: "sqlite3"
  database: /home/forrest/Projects/go-servers/buffalo/coke_coke_test.sqlite

production:
  dialect: "sqlite3"
  database: /home/forrest/Projects/go-servers/buffalo/coke_coke_production.sqlite
